micronaut:
  application:
    name: flightPub

  views:
    folder: views

  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:static
    freemarker:
      enabled: true
      suffix: .ftl

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    dialect: SQL_SERVER
    db-type: mssql
    url: jdbc:sqlserver://flightpub-protodb.database.windows.net:1433;database=flightpub-protodb;user=FlightPubAdmin@flightpub-protodb;password={FlightPub1};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  
